FROM node:20-alpine

WORKDIR /home/node/app

COPY npm/package.json npm/package-lock.json npm/index.js npm/webpack.config.js ./

COPY npm/src/index.js src/index.js

RUN set -ex; \
    npm install; \
    npx webpack;

# Exclude node package manager packages
RUN rm -rf /usr/local/lib/node_modules

CMD ["node", "./index.js"]